name: .Net Core Package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build 
    
    - run: dotnet nuget push /home/runner/work/sample-artifact-nuget/sample-artifact-nuget/bin/Debug/SampleArtifact.1.0.0.nupkg -k ${{ secrets.GITHUB_TOKEN }} -s https://nuget.pkg.github.com/demoserievideo/index.json

    
