name: .Net Core Package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
        source-url: https://nuget.pkg.github.com/demoserievideo/index.json
      env:
        NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
   
    - name: Install dependencies
      run: dotnet restore
   
    - name: Build
      run: dotnet build 
    
    - run: dotnet nuget push ./sample-artifact-nuget/**/*.nupkg --skip-duplicate --no-symbols true

    
