name: .Net Core Package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
        source-url: https://nuget.pkg.github.com/demoserievideo/index.json
      env:
        NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
   
    - name: Install dependencies
      run: dotnet restore
   
    - name: Build
      run: dotnet build 

    - name: Add private GitHub registry to NuGet
      run: nuget sources add -name "GH" -Source https://nuget.pkg.github.com/demoserievideo/index.json -Username julioarruda -Password ${{ secrets.GITHUB_TOKEN }}

    - run: dotnet nuget push ./**/*.nupkg --skip-duplicate --no-symbols true -s GH

    
